# Generated by Django 6.0.8 on 2026-08-20 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('onboarding_greeting', 'Onboarding: greeting'), ('onboarding_occupation', 'Onboarding: occupation'), ('onboarding_bank_link', 'Onboarding: bank link'), ('onboarding_pfa_selection', 'Onboarding: PFA selection'), ('onboarding_consent', 'Onboarding: consent'), ('onboarding_pin_setup', 'Onboarding: PIN setup'), ('idle', 'Idle'), ('awaiting_confirmation', 'Awaiting confirmation'), ('awaiting_pin', 'Awaiting PIN'), ('expired', 'Expired')], default='onboarding_greeting', max_length=25)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('twilio_message_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('body', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('interactive_reply', 'Interactive reply'), ('template', 'Template'), ('media', 'Media')], default='text', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='conversations.conversationsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='conversatio_user_id_88855c_idx')],
            },
        ),
    ]
