# Generated by Django 6.0.8 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='state',
            field=models.CharField(choices=[('onboarding_greeting', 'Onboarding: greeting'), ('onboarding_occupation', 'Onboarding: occupation'), ('onboarding_bank_link', 'Onboarding: bank link'), ('onboarding_pfa_selection', 'Onboarding: PFA selection'), ('onboarding_pfa_link', 'Onboarding: existing RSA PIN or new'), ('onboarding_consent', 'Onboarding: consent'), ('onboarding_pin_setup', 'Onboarding: PIN setup'), ('idle', 'Idle'), ('awaiting_confirmation', 'Awaiting confirmation'), ('awaiting_pin', 'Awaiting PIN'), ('expired', 'Expired')], default='onboarding_greeting', max_length=25),
        ),
    ]
