# Generated by Django 6.0.8 on 2026-08-20 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('intent_classification', 'Intent classification'), ('recommendation_generation', 'Recommendation generation')], max_length=30)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('raw_prompt', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_output', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('fallback_used', 'Fallback used')], max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
