# Generated by Django 6.0.8 on 2026-08-20 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_provisioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransactionmirror',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercalllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='banktransactionmirror',
            index=models.Index(fields=['user', '-occurred_at'], name='account_pro_user_id_18ae1c_idx'),
        ),
    ]
