# Generated by Django 6.0.8 on 2026-08-20 08:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. +2348012345678', regex='^\\+[1-9]\\d{7,14}$')])),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('occupation_type', models.CharField(blank=True, choices=[('trader', 'Trader'), ('artisan', 'Artisan'), ('pos_agent', 'POS Agent'), ('tailor', 'Tailor'), ('mechanic', 'Mechanic'), ('market_woman', 'Market Woman'), ('other', 'Other')], max_length=20)),
                ('onboarding_state', models.CharField(choices=[('started', 'Started'), ('occupation_selected', 'Occupation selected'), ('bank_linked', 'Bank linked'), ('consent_given', 'Consent given'), ('pin_set', 'PIN set'), ('completed', 'Completed')], default='started', max_length=25)),
                ('transaction_pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data processing'), ('terms_of_service', 'Terms of service'), ('pin_setup', 'PIN setup')], max_length=25)),
                ('consent_text_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField()),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('source_message_sid', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
    ]
