# Generated by Django 6.0.8 on 2026-08-20 08:52

import django.core.validators
import django.db.models.deletion
import pensions.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPFASubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rsa_pin', models.CharField(db_index=True, max_length=20)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('remittance_ref', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(default='successful', max_length=15)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MockPFARegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('rsa_pin', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('not_registered', 'Not registered'), ('pending', 'Pending'), ('registered', 'Registered'), ('failed', 'Failed')], max_length=15)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_pfa_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('contribution', 'Contribution'), ('adjust_schedule', 'Adjust schedule')], max_length=20)),
                ('proposed_payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('executing', 'Executing'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('expires_at', models.DateTimeField(default=pensions.models.default_expiry)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('pin_verified', models.BooleanField(default=False)),
                ('confirmation_message_sid', models.CharField(blank=True, max_length=64)),
                ('decline_reason', models.CharField(blank=True, max_length=50)),
                ('ai_interaction_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='ai_engine.aiinteractionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PensionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=10)),
                ('retirement_target_age', models.PositiveSmallIntegerField(default=60)),
                ('emergency_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Fraction of each confirmed contribution routed to the emergency fund; the rest goes to retirement. Deterministic split - never set by AI.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('0.50'))])),
                ('preferred_pfa', models.CharField(blank=True, choices=[('stanbic_ibtc', 'Stanbic IBTC Pension Managers'), ('arm', 'ARM Pension Managers'), ('leadway_pensure', 'Leadway Pensure PFA'), ('fcmb', 'FCMB Pensions'), ('pal', 'Pensions Alliance Limited (PAL)'), ('trustfund', 'Trustfund Pensions'), ('crusader_sterling', 'Crusader Sterling Pensions'), ('premium', 'Premium Pension'), ('sigma', 'Sigma Pensions'), ('fidelity', 'Fidelity Pension Managers'), ('parthian', 'Parthian Pensions'), ('citizens', 'Citizens Pensions')], max_length=25)),
                ('rsa_pin', models.CharField(blank=True, max_length=20)),
                ('pfa_registration_status', models.CharField(choices=[('not_registered', 'Not registered'), ('pending', 'Pending'), ('registered', 'Registered'), ('failed', 'Failed')], default='not_registered', max_length=15)),
                ('pfa_registered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pension_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyFund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_fund', to='pensions.pensionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributionSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('per_income_event', 'Per income event'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pensions.pensionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('destination', models.CharField(choices=[('emergency_fund', 'Emergency fund'), ('retirement_fund', 'Retirement fund')], max_length=20)),
                ('bank_transfer_reference', models.CharField(blank=True, max_length=128)),
                ('pfa_remittance_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('failed', 'Failed'), ('reversed', 'Reversed')], max_length=10)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('pending_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='pensions.pendingaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='pensions.pensionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetirementTracker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('readiness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('readiness_label', models.CharField(blank=True, max_length=50)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_tracker', to='pensions.pensionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pendingaction',
            index=models.Index(fields=['user', 'status'], name='pensions_pe_user_id_1f5c3f_idx'),
        ),
    ]
