# Generated by Django 6.0.8 on 2026-08-20 10:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionplan',
            name='emergency_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='Fraction of each confirmed contribution routed to the emergency fund; the rest goes to retirement. Deterministic split - never set by AI.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('0.50'))]),
        ),
    ]
